# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define WebVisualizer service
  ia_web_visualizer:
    depends_on:
      - ia_common
    build:
      context: $PWD/../WebVisualizer
      dockerfile: $PWD/../WebVisualizer/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    read_only: true
    image: ${DOCKER_REGISTRY}ia_web_visualizer:${EIS_VERSION}
    container_name: ia_web_visualizer
    hostname: ia_web_visualizer
    network_mode: host
    restart: unless-stopped
    ipc: "none"
    environment:
      AppName: "WebVisualizer"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_PREFIX: ${ETCD_PREFIX}

      # MessageBus Endpoint Configuration
      CertType: "zmq,pem"
      ZMQ_RECV_HWM: "50"

      # Use IPC mode (zmq_ipc) when VideoIngestion, VideoAnalytics and Visualizer
      # based containers are running on the same host. If they are running on diff
      # host, please use TCP mode for communication.
      # Eg: Stream cfg for
      # IPC: zmq_ipc, <absolute_socket_directory_path>
      # TPC: zmq_tcp, <publisher_host>:<publisher_port>

      # For default video streaming usecase alone
      SubTopics: "VideoAnalytics/camera1_stream_results"
      camera1_stream_results_cfg : "zmq_tcp,127.0.0.1:65013"
    user: ${EIS_UID}
    volumes:
      - "vol_eis_socket:${SOCKET_DIR}"
      - "vol_temp_webv:/var/tmp"
    secrets:
      - ca_etcd
      - etcd_WebVisualizer_cert
      - etcd_WebVisualizer_key

volumes:
  vol_temp_webv:
    driver: local
    driver_opts:
      type: tmpfs
      o: "size=5K"
      device: tmpfs

secrets:
  etcd_WebVisualizer_cert:
    file: provision/Certificates/WebVisualizer/WebVisualizer_client_certificate.pem
  etcd_WebVisualizer_key:
    file: provision/Certificates/WebVisualizer/WebVisualizer_client_key.pem
