version: '3.6'

services:
  ## Define WebVisualizer service
  ia_web_visualizer:
    depends_on:
      - ia_common
    build:
      context: $PWD/../WebVisualizer
      dockerfile: $PWD/../WebVisualizer/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    # read_only: true
    image: ${DOCKER_REGISTRY}ia_web_visualizer:${EIS_VERSION}
    container_name: ia_web_visualizer
    hostname: ia_web_visualizer
    network_mode: host
    restart: unless-stopped
    command: ["pcb_demo_label.json"]
    environment:
      AppName: "WebVisualizer"
      IMAGE_DIR: ${EIS_INSTALL_PATH}/saved_images
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${no_proxy}

      # MessageBus Endpoint Configuration
      CertType: "zmq,pem"
      ZMQ_RECV_HWM: "1000"

      # Use IPC mode (zmq_ipc) when VideoIngestion, VideoAnalytics and Visualizer
      # based containers are running on the same host. If they are running on diff
      # host, please use TCP mode for communication.
      # Eg: Stream cfg for
      # IPC: zmq_ipc, <absolute_socket_directory_path>
      # TPC: zmq_tcp, <publisher_host>:<publisher_port>

      # For default video streaming usecase alone
      SubTopics: "VideoAnalytics/camera1_stream_results"
      camera1_stream_results_cfg : "zmq_tcp,127.0.0.1:65013"

    volumes:
      - "${EIS_INSTALL_PATH}/saved_images:${EIS_INSTALL_PATH}/saved_images"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "vol_eis_socket:${SOCKET_DIR}"
    secrets:
      - ca_etcd
      - etcd_WebVisualizer_cert
      - etcd_WebVisualizer_key

secrets:
  etcd_WebVisualizer_cert:
    file: provision/Certificates/WebVisualizer/WebVisualizer_client_certificate.pem
  etcd_WebVisualizer_key:
    file: provision/Certificates/WebVisualizer/WebVisualizer_client_key.pem